-- ============================================================
-- SCRIPT DE CONFIGURACIÓN COMPLETA PARA SUPABASE
-- Sistema de Gestión de Trabajadores JC & Villagran
-- ============================================================

-- 1. ELIMINAR TABLAS EXISTENTES (si las hay)
DROP TABLE IF EXISTS public.authorized_users CASCADE;
DROP TABLE IF EXISTS public.workers CASCADE;

-- 2. ELIMINAR FUNCIONES Y TRIGGERS EXISTENTES
DROP TRIGGER IF EXISTS update_authorized_users_updated_at ON public.authorized_users;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;

-- ============================================================
-- TABLA: workers (Trabajadores)
-- ============================================================

CREATE TABLE public.workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cedula TEXT NOT NULL UNIQUE,
    cargo TEXT NOT NULL,
    turno TEXT NOT NULL,
    estado TEXT NOT NULL,
    telefono TEXT NOT NULL,
    documentos JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS para workers
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;

-- Política: Permitir acceso público a workers (para desarrollo)
-- En producción, deberías restringir esto
CREATE POLICY "Allow public read access" ON public.workers
    FOR SELECT USING (true);

CREATE POLICY "Allow all access for anon users" ON public.workers
    FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- TABLA: authorized_users (Sistema de Autenticación)
-- ============================================================

CREATE TABLE public.authorized_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nombre TEXT NOT NULL,
    rol TEXT DEFAULT 'admin',
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS para authorized_users
ALTER TABLE public.authorized_users ENABLE ROW LEVEL SECURITY;

-- Políticas para authorized_users
CREATE POLICY "Allow public read for login" ON public.authorized_users
    FOR SELECT USING (activo = true);

CREATE POLICY "Allow all for authenticated" ON public.authorized_users
    FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- FUNCIÓN Y TRIGGER: Actualizar updated_at automáticamente
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_authorized_users_updated_at
    BEFORE UPDATE ON public.authorized_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- INSERTAR USUARIO ADMINISTRADOR POR DEFECTO
-- ============================================================

INSERT INTO public.authorized_users (email, password_hash, nombre, rol, activo)
VALUES (
    'admin@jcvillagran.cl',
    'admin123',
    'Administrador',
    'admin',
    true
);

-- ============================================================
-- VERIFICACIÓN: Mostrar datos insertados
-- ============================================================

SELECT 
    '✅ Usuario admin creado correctamente' as status,
    email,
    nombre,
    rol,
    activo
FROM public.authorized_users 
WHERE email = 'admin@jcvillagran.cl';

-- ============================================================
-- INSTRUCCIONES DE USO
-- ============================================================

-- 1. Copia TODO este archivo
-- 2. Ve al SQL Editor en tu proyecto de Supabase
-- 3. Pega el contenido completo
-- 4. Haz clic en "Run" o presiona Ctrl/Cmd + Enter
-- 5. Verifica que aparezca el mensaje de éxito al final
-- 6. Credenciales de login:
--    Email: admin@jcvillagran.cl
--    Password: admin123
-- 7. IMPORTANTE: Cambia la contraseña después del primer login

-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
