-- ============================================================
-- CONFIGURACIÓN DE AUTENTICACIÓN DESDE CERO
-- Sistema de Whitelist para JC & Villagran
-- ============================================================

-- PASO 1: Crear tabla de usuarios autorizados
CREATE TABLE public.authorized_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nombre TEXT NOT NULL,
    rol TEXT DEFAULT 'admin',
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- PASO 2: Habilitar Row Level Security (RLS)
ALTER TABLE public.authorized_users ENABLE ROW LEVEL SECURITY;

-- PASO 3: Crear políticas de acceso
-- Política 1: Permitir lectura pública (necesaria para login)
CREATE POLICY "allow_public_select" 
ON public.authorized_users
FOR SELECT 
TO anon, authenticated
USING (activo = true);

-- Política 2: Permitir todas las operaciones (para gestión de whitelist)
CREATE POLICY "allow_all_operations" 
ON public.authorized_users
FOR ALL 
TO anon, authenticated
USING (true) 
WITH CHECK (true);

-- PASO 4: Crear función para actualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- PASO 5: Crear trigger
CREATE TRIGGER update_authorized_users_updated_at
BEFORE UPDATE ON public.authorized_users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- PASO 6: Insertar usuario admin por defecto
INSERT INTO public.authorized_users (email, password_hash, nombre, rol, activo)
VALUES (
    'admin@jcvillagran.cl',
    'admin123',
    'Administrador',
    'admin',
    true
);

-- PASO 7: Verificar que todo funciona
SELECT 
    '✅ CONFIGURACIÓN COMPLETADA' as status,
    id,
    email,
    nombre,
    rol,
    activo,
    created_at
FROM public.authorized_users 
WHERE email = 'admin@jcvillagran.cl';

-- ============================================================
-- INSTRUCCIONES:
-- 1. Copia TODO este contenido
-- 2. Ve a Supabase SQL Editor
-- 3. Pega y ejecuta (Run)
-- 4. Deberías ver el mensaje "✅ CONFIGURACIÓN COMPLETADA"
-- 5. Credenciales: admin@jcvillagran.cl / admin123
-- ============================================================
