-- 1. Eliminar la tabla existente si es necesario (opcional, ten cuidado si ya tienes datos)
-- DROP TABLE IF EXISTS public.workers;

-- 2. Crear la tabla "workers"
CREATE TABLE IF NOT EXISTS public.workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cedula TEXT NOT NULL UNIQUE,
    cargo TEXT NOT NULL,
    turno TEXT NOT NULL,
    estado TEXT NOT NULL,
    telefono TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar Row Level Security (RLS) - ¡Importante para la seguridad!
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas para permitir el acceso
-- Esta política permite a cualquier persona (anon) leer todos los datos.
CREATE POLICY "Allow public read access" ON public.workers
    FOR SELECT USING (true);

-- Esta política permite a cualquier persona (anon) insertar, actualizar y eliminar datos.
-- Para un entorno de producción, deberías restringir esto a usuarios autenticados.
CREATE POLICY "Allow all access for anon users" ON public.workers
    FOR ALL USING (true)
    WITH CHECK (true);

-- 5. Insertar datos de ejemplo (opcional)
-- Esto solo se insertará si la tabla está vacía y las cédulas no existen.
INSERT INTO public.workers (nombre, cedula, cargo, turno, estado, telefono)
VALUES
    ('Juan Pérez Ejemplo', '12345678', 'Supervisor', 'Diurno', 'Activo', '555-0123'),
    ('María González Ejemplo', '87654321', 'Guardia', 'Nocturno', 'Activo', '555-0124')
ON CONFLICT (cedula) DO NOTHING;
